name: Build Proxy DLL Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 编译 原DLL + 代理DLL + 测试EXE
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: 构建所有文件
        run: |
          cl /LD MyDll_original.cpp /Fe:MyDll_original.dll
          cl /LD MyDll.cpp /link /DEF:MyDll.def /Fe:MyDll.dll
          cl Test.cpp /Fe:Test.exe

      - name: 上传全部产物
        uses: actions/upload-artifact@v4
        with:
          name: Demo-Files
          path: |
            MyDll_original.dll
            MyDll.dll
            Test.exe
